[[snippets]]
  description = "Search an organization by a domain name"
  command = "http organizations.develop.paris-squad.com/api/organizations/ Authorization:\"Bearer <token>\" | jq  '. [] | select(.domain | contains(\"percipio\"))'"
  output = ""

[[snippets]]
  description = "Decode a base64 value"
  command = "echo \"ZWxhc3RpY2FjaGUtcmVkaXMuaTVmbmhpLjAwMDEudXNlMS5jYWNoZS5hbWF6b25hd3MuY29t\" | base64 -D"
  output = ""

[[snippets]]
  description = "Get an auth token for auth0"
  command = "https yassin.eu.auth0.com/oauth/token grant_type=\"http://auth0.com/oauth/grant-type/password-realm\" audience=\"http://percipio.com/global\" client_id=\"SncWzgm7PKQi4lSIhWu5ivvhMdkYzYMr\" username=\"admin@artisan.com\" password=\"test1234\" scope=\"openid app_metadata\" realm=\"ucmv2\" client_secret=\"gkCZZO9TR-Ty8AmB2Iz1lVmLvXjuZJuHgA4CgZlZDxGC-x8TAqrGHGvloprb1Mxn\""
  output = ""

[[snippets]]
  description = "Get a fresh new jwt and decode it"
  command = "https yassin.eu.auth0.com/oauth/token grant_type=\"http://auth0.com/oauth/grant-type/password-realm\" audiencce=\"http://percipio.com/global\" client_id=\"SncWzgm7PKQi4lSIhWu5ivvhMdkYzYMr\" username=\"admin@artisan.com\" password=\"test1234\" scope=\"openid app_metadata\" realm=\"ucmv2\" client_secret=\"gkCZZO9TR-Ty8AmB2Iz1lVmLvXjuZJuHgA4CgZlZDxGC-x8TAqrGHGvloprb1Mxn\" | jq \". .id_token\" | xargs jwt decode"
  output = ""

[[snippets]]
  description = "See log of the previous started pod. Usefull wwwhen pod always crash"
  command = "kubectl logs <pod-name> --previous"
  output = ""

[[snippets]]
  description = "Get only header of the api response"
  command = "http -p h <api-url>"
  output = ""

[[snippets]]
  description = "Upload a base64 csv file to lbe"
  command = "echo '{\"csv\":{\"data\":\"test\"}}' | jq --arg data `base64 -i <path/to/your/csv>` 'setpath([\"csv\", \"data\"]; $data)' | http \"backoffice.artisan.dev/v1/admin/csv_user_imports\" Authorization:\"Bearer <your_jwt>\""
  output = ""
